#workflow name
name: "PrismaDemo"

on: 
  push:
    branches:
      - master
jobs:
  pm2-configuration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install pm2@latest -g
      - run: pm2 -V
      - run: pm2 list
      - run: pm2 restart ecosystem.config.js